#!/bin/sh
docker pull daison12006013/lucid
docker container rm -f lucid-container
# | detach
# | ports        [host <- guest]:
#     lucid      [8330 <- 8330]
#     sveltekit  [8331 <- 8331]
#     docs       [8332 <- 8332]
# | container name to "lucid-container" from daison12006013/lucid image
# | mount current folder to container's /app folder
docker run \
    -v $(PWD)/src/lucid:/app/lucid \
    -v $(PWD)/src/lucid-ui:/app/lucid-ui \
    -d \
    -p 8330:8330 \
    -p 8331:8331 \
    -p 8332:8332 \
    --name lucid-container daison12006013/lucid

# re-build again after mounting the folder to sync the files
docker exec -it lucid-container sh -c "(cd /app/lucid && sh /app/lucid/cmd/install-reflex.sh) && exit"
docker exec -it lucid-container sh -c "(cd /app/lucid && sh /app/lucid/cmd/check-binaries.sh) && exit"
docker exec -it lucid-container sh -c "(cd /app/lucid && sh /app/lucid/cmd/build-go.sh) && exit"
docker exec -it lucid-container sh -c "(cd /app/lucid-ui && sh /app/lucid-setup/scripts/build-svelte.sh) && exit"
